### ISSUE TITLE
Can't find documentation for profile-file.b3270

### ISSUE THREAD

**Issue by stewartfrancis** [pmattes/x3270#21]
Hey, I was hoping to conduct an experiment using b3270 and got stuck trying to launch it.

I was able to build b3270 from your master branch, but I wasn't able to establish a connection.  The command line help seems a bit ambiguous here - if I try displaying the help:

```
$ b3270 --help
Usage: b3270 [options] [[prefix:][LUname@]hostname[:port]]
```

It shows syntax where I can specify the connection details on the command line.  If I try that:

```
b3270 example.com:22
Unrecognized option(s)
Usage: b3270 [options] [profile-file.b3270]
Use --help for the list of options
```

I get asked to supply a profile file.  I could see some reference to creating this from the UI for `wx3270` in the wiki, but no reference to the format for this file so I could create one without `wx3270`.  Hoping you'll be able to point me in the right direction, thanks!

**Comment by pmattes** [comment]
The fix for the usage message bug has been committed to the 4.1 and master branches.
