### ISSUE TITLE
docs: broken suite3270-4.1ga11-src.tgz download link

### ISSUE THREAD

**Issue by chimurai** [pmattes/x3270#25]
Thanks for the new 4.1ga11 release.

On https://x3270.miraheze.org/wiki/Downloads there is a broken link to http://x3270.bgp.nu/download/04.01/suite3270-4.1ga11-src.tgz

This link is used to update the `x3270` brew formula.
https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+x3270+is%3Aclosed

**Comment by pmattes** [comment]
Fixed.
