### ISSUE TITLE
IPv6 / IPv4 failover

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#27]
PROBLEM: If a hostname has both an IPv6 and IPv4 address in DNS, x3270 will try the IPv6 protocol and then give up.  This is problem (for example) when an IPv6 enabled host has an an application (such Hercules SpinHawk) with  IPv4 only ports. his especially a problem when connecting to common standard hostnames such as `localhost`. 

This behavior differs from programs such as `telnet`, `ssh`, and web browsers, which automatically try both protocols.   

EXPECTED BEHAVIOR: x3270 and other programs in the suite should automatically try both IPv4 and IPv6 ports after common errors such as connection refused or host unreachable.

OPTIONAL BEHAVIOR: The programs can be directed by configuration or comment line to only use IPv4 or IPv6 protocol via configuration or command line switch (other than the host parameter)

**Comment by Rhialto** [comment]
My guess is (and I admit I totally didn't check the code due to lack of
time) that the older function gethostbyname(3) is used to find the
address of the given host. There is now getaddrinfo(3) which is easier
to use in case of a host name with multiple addresses and/or multiple
protocols. The manual page has a nice example of how to use it both as a
client and a server. The former tries connecting to all possible
addresses in turn and the latter binds a listening socket to all of them.

**Comment by pmattes** [comment]
The code does use getaddrinfo(). But it uses only the first entry returned, instead of trying multiple entries in sequence.

I will get a fix for this into 4.2. A back-port to 4.1 is possible but might take a bit longer.

**Comment by pmattes** [comment]
Correction: The code does accept and try up to 4 entries returned by getaddrinfo, and I just verified that it tries each of them. @swhobbit, can you give me more details about how this is not working as you expect? And what version of the code are you using?

**Comment by swhobbit** [comment]
[16,/tmp,56] uname -a                                                                       
**Linux pepe-le-pew 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux**

[16,/tmp,62] 'x3270' -v                                                      
**x3270 v4.2pre1 Thu Nov 25 06:26:04 UTC 2021 ahd**
Build options: --enable-local-process
_(code & copyright pages omitted)_

host hercules                                                                  
**hercules.hh.kew.com has address 192.168.203.5
hercules.hh.kew.com has IPv6 address 2001:470:B:625:5:5:5:5**
host hercules-4                                                                
**hercules-4.hh.kew.com has address 192.168.203.5**
host hercules-6                                                                
**hercules-6.hh.kew.com has IPv6 address 2001:470:B:625:5:5:5:5**                  
                                                             
**_Runs with traces_**
[16,/tmp,53] 'x3270' -trace hercules 32705               # fails (uses IPv4)    [x3trc.31869-hercules.txt](https://github.com/pmattes/x3270/files/8166554/x3trc.31869-hercules.txt)
                                    
[16,/tmp,54] 'x3270' -trace hercules-4 32705           # Works [x3trc.31881-hercules-4.txt](https://github.com/pmattes/x3270/files/8166555/x3trc.31881-hercules-4.txt)                                    

[16,/tmp,55] 'x3270' -trace hercules-6 32705           # fails      [x3trc.31909-hercules-6.txt](https://github.com/pmattes/x3270/files/8166556/x3trc.31909-hercules-6.txt)

**Comment by pmattes** [comment]
The fix for this has been committed to 4.1 and master (4.2). I plan to add -4 and -6 options to master shortly.

**Comment by swhobbit** [comment]
Tested on Linux system that bug was reported on.  It now works, trying ::1 (IPv6) and then 127.0.0.1
