### ISSUE TITLE
x3270 on file transfer screen: ```Delete``` key (next to ```End``` key) is evil

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#30]
While I realize the X 3270 v4 file transfer screen is due to be completely replaced, and thus it has a notarized DNR order, _please_ fix two small things.

- The truly evil action is that the ```Delete``` key (next to the ```End``` key) **deletes left** like the ```Backspace``` key instead of the _correct_ action of **delete under.**  The key works properly in terminal mode 
- The usual ```Ctrl-V``` (or ```Cmd-V```) key doesn't do _anything_; it _should_ **paste**.  The ```Left Mouse Button``` does **paste**.  (But I only remember try the button after the keys fail!)

**Comment by swhobbit** [comment]
Two related trivia questions: 

In the default key map, for the ```Delete``` key, I see no ```Delete()``` action, but in x3270 mode it Does the Right Thing.  Why?  :-)

When writing a keymap, what's the difference between a ```<Key>``` and a ```<Keypress>```?

**Comment by swhobbit** [comment]
FYI: Testing was was Linux pepe-le-pew 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

(A Raspberry Pi 4)

**Comment by pmattes** [comment]
> In the default key map, for the `Delete` key, I see no `Delete()` action, but in x3270 mode it Does the Right Thing. Why? :-)

The catch-all Default() action Does the Right Thing for a number of common keystrokes, including Delete.

> When writing a keymap, what's the difference between a `<Key>` and a `<Keypress>`?

None. <Key> is an alias for <KeyPress>. There is also a <KeyRelease> event, by the way.

**Comment by pmattes** [comment]
> While I realize the X 3270 v4 file transfer screen is due to be completely replaced, and thus it has a notarized DNR order, _please_ fix two small things.
> 
> * The truly evil action is that the `Delete` key (next to the `End` key) **deletes left** like the `Backspace` key instead of the _correct_ action of **delete under.**  The key works properly in terminal mode
> * The usual `Ctrl-V` (or `Cmd-V`) key doesn't do _anything_; it _should_ **paste**.  The `Left Mouse Button` does **paste**.  (But I only remember try the button after the keys fail!)

On it.

**Comment by pmattes** [comment]
Fixed in 4.2.

Note that the x3270 dialog input fields in dialogs now have similar behavior to the main window with regard to copy and paste. Highlighting with the mouse copies the selected area to the PRIMARY selection. Control-C copies the highlighted area to the CLIPBOARD selection. The middle mouse button pastes from PRIMARY. Control-V pastes from CLIPBOARD. This is consistent with other X11 applications.

**Comment by swhobbit** [comment]
> Highlighting with the mouse copies the selected area to the PRIMARY selection. Control-C copies the highlighted area to the CLIPBOARD selection. The middle mouse button pastes from PRIMARY. Control-V pastes from CLIPBOARD. This is consistent with other X11 applications.

SGTM
