### ISSUE TITLE
Inserting into a full field locks the keyboard after the first character is accepted

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#31]
_Problem_: When typing on a screen such as a full screen editor (PDF, RFE, REVEDIT, XEDIT) IN X3270, and one is insert mode entering full field (such the prefix command area), it locks the keyboard **after** the first character is placed on the screen..  

_Expected behavior:_ The keyboard should lock **before** updating the screen with the first character.

**Comment by pmattes** [comment]
Truly embarrassing. I wonder when it broke.

**Comment by pmattes** [comment]
It broke in 4.0. Fixed now in 4.1 and master (4.2).
