### ISSUE TITLE
the default scheme on …/wiki/ColorScheme_resource … isn't

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#38]
The color scheme named "default" on https://x3270.miraheze.org/wiki/ColorScheme_resource does not match the x3270 color scheme in the source.  It should be renamed "sample" or another name, and a sample "x3270.colorScheme" resource added above it in the example to show to point at it.

(Inserting the actual default would be problematic as soon as the source is edited.)

**Comment by pmattes** [comment]
I've simply updated the Wiki to show the actual default.
