### ISSUE TITLE
the greenScreen resource in the source does not properly emulate a real 3278

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#39]
The x3270 resource x3270.colorScheme.GreenScreen does an incomplete job of emulating a real 3270, as it fails to show what fields are highlighted.

As the x3278 is actually using the GreenScreen the 3279 color map: knowing the default attributes for the four colors (see [https://en.wikipedia.org/wiki/IBM_3270#3279](https://en.wikipedia.org/wiki/IBM_3270#3279)), the map can be changed to do use a default green for high intensity fields like so:

```
x3270.colorScheme.kewGreenScreen: \
        Green3 Green3 green  Green3  \
        Green3 Green3 Green3 green \
        Green3 Green3 Green3 Green3 \
        Green3 Green3 Green3 green \
        white gray10 dimGrey \
        4 2 1 15
```

**Comment by swhobbit** [comment]
I updated x3270.colorScheme.kewGreenScreen, it some colors in the map wrong.

**Comment by pmattes** [comment]
I appreciate the suggestion, but I am removing 'green screen' from the color scheme menu instead, since it is more of a toy than anything of practical use. If you want a green screen, use 3278 emulation, not a color scheme that maps the real 3279 colors onto shades of green.
