### ISSUE TITLE
Question: When do you plan to release version 4.0?

### ISSUE THREAD

**Issue by ILoveHubGit** [pmattes/x3270#4]
I'm very pleased with the new JSON support of the API. This will make it so much easier to built an application using this API.
However, maybe in the very near future I can start with a new application which will use the API of wc3270. But because this application will run in a production environment I can't use an alpha version.
Therefore my question but no pressure, just asking.
When do you think to release version 4.0?

**Comment by pmattes** [comment]
I tend to tinker with things too long. ;-)

Here is the planned schedule:
Beta release (4.0beta7): April 25th, 2020.
Additional Beta releases as issues are identified and fixed.
GA release: May 25th, 2020.

**Comment by swhobbit** [comment]
> I tend to tinker with things too long. ;-)

“There comes a time in every project when you must shoot the engineers and begin production.”
