### ISSUE TITLE
Black is Black (I want my window edges back)

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#40]
A problem which occurs on x3270 on environments with minimal frames (including `Xquartz` on `MacOS`) is that Windows seem run into each see other, as shown on left in the in the attached screen show.  On right are two screen with the background changed from true `black` to `gray10`. `gray10` creates subtle difference from `black` (used on the actually border) which delineates
windows borders without being intrusive.

I would suggest all applicable schemes be changed to use gray10 instead of black.

**Comment by pmattes** [comment]
Done.
