### ISSUE TITLE
The x3270 bright color scheme on …/wiki/ColorScheme_resource … isn't

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#41]
The provide x3270 color scheme `bright` isn't: It's a clone of the default 3279 scheme.  Th colros needing the most help are `green` and `blue`, which are tweaked below:

```
x3270.colorScheme.bright: \
       black DodgerBlue red hotpink \
       limegreen turquoise yellow white \
       gray10 blue3 orange purple \
       paleGreen paleTurquoise2 grey white \
       white black dimGrey \
       4 2 1 15
```

**Comment by pmattes** [comment]
It's actually 'default' that was cloned from 'bright'.

I have removed 'bright' from the menu, though the underlying resource is still there for folks who depend on it.

**Comment by swhobbit** [comment]
_whoops_

A major point (which I did note but failed to highlight) was that the default green and blue are too dark, especially in (thin) default font. If you're going to delete the `bright` color scheme, consider the colors `DodgerBlue` and `limegreen` on the default scheme.

FYI: The LCM+L VM/SP machine now the `PALETTE EXEC` which I use to display all the colors.

**Comment by pmattes** [comment]
I have applied your color suggestions to the default color scheme. (I've got a cool generated screen here with various color and attribute options for testing.)

**Comment by swhobbit** [comment]
Our job is done here. :-)  

(You already closed it.).
