### ISSUE TITLE
"You're in a maze of little wiki pages, all useless …"

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#43]
The x3270 wiki is populated with numerous pages with the entire contents similar to:

>  [_fee_] sets _fi_ to _fo_.

where **_fi_** is a manual link to the wiki page for it.

Such stub pages should changed to **automatically** redirect to the referenced target wiki page, and the target page updated to include the extra (trivial) documentation.

**Comment by pmattes** [comment]
They're not stub pages. They have actual content, albeit relatively little most of the time.

The command-line option pages tell you which emulators support that option (the list of categories at the bottom), they give the value of the resource they set if they do not take a parameter, and sometimes give other useful information, such as whether they are standard Xt options or x3270-specific.

IMO, needing to do one extra click to get to the 'meat' of a command-line option is not an undue burden. The command-line options pages are not dead ends.

As for the resource pages often being less than entirely useful, I sympathize. The Wiki is really weak on tying concepts together usefully. Related pages are usually hyperlinked to each other, but there are not enough pages that cover more general topics like 'how to set up the colors in x3270'. I am working on that, and I am open to specific suggestions for topics that should be added and how best to organize them.

**Comment by swhobbit** [comment]
> They're not stub pages. They have actual content, albeit relatively little most of the time.

Wikipedia.Org flag many pages with some real content as "stub pages". 

> The command-line option pages tell you which emulators support that option (the list of categories at the bottom), they give the value of the resource they set if they do not take a parameter, and sometimes give other useful information, such as whether they are standard Xt options or x3270-specific.
> 
> IMO, needing to do one extra click to get to the 'meat' of a command-line option is not an undue burden. The command-line options pages are not dead ends.

They are _not_ one click and they _are_ dead ends when they are not the options you are looking for.  You forget that you know all the options cold, and thus you always click the right option. But you are not the audience.  (I'm sorry.)  It's a <expletive> maze to the rest of us.

Example: last night I was Easter egging for the host prefix to disable extended negotiation, and when I hit the category page list of 4 (?) options I basically opened ALL of them in a new tabs and then iterated through them.

I am reminded of a UNIX fortune:

> _"I'm sure that VMS is completely documented, I just haven't found the right manual yet.  I've been working my way through the manuals in the document library and I'm half way through the second cabinet, (3 shelves to go), so I should find what I'm looking for by mid May.  I hope I can remember what it was by the time I find it_."  -- Alex Crain

> I am open to specific suggestions 

My **only** suggestion (and the title of this issue) is lose every one sentence page in the wiki and thus make the maze smaller. Yes it's hard work.  Otherwise close this issue as "wontfix" and I'll STFU (and be sad).

(If wonder how I know of what I speak of work scope, I documented [UUPC/extended](https://github.com/swhobbit/UUPC); the [monolithic document](https://www.uupc.net/pub/uupc/1.13k/upc13kap.zip) runs 231 pages with appendices. It took me years wall clock. By the time I was done, UUCP was obsolete.)

**Comment by pmattes** [comment]
I forget the names of options/resources/prefixes all the time, and I even forget whether it is an option or prefix that controls a particular behavior. But you are right, I am not the primary target audience for the wiki.

I don't want you to simply STFU, because I need other people's perspectives on the usability of the wiki.

However, I don't find the advice to simply get rid of all of the short pages very helpful. Some may be easy pickings, but getting rid of others would simply turn the fan-out problem (lots of little pages) into a fan-in problem (gigantic pages that need to list all of the variations and exceptions for each of the different emulators).

I agree that trying to find the right host prefix can be exquisitely frustrating. That's something I can work on. If you have other examples of particularly difficult quests for information, I'm happy to hear about them.

**Comment by pmattes** [comment]
I've condensed the splatter of host prefixes down to one table on the 'Host name syntax' page.

**Comment by swhobbit** [comment]
> I don't want you to simply STFU, because I need other people's perspectives on the usability of the wiki.

This actually a narrow (if important) bug.  I didn't mean to imply I'd disappear completely relative to the Wiki or otherwise.

**Comment by pmattes** [comment]
The command-line options pages for each emulator now consist of a summary table giving the basic syntax and meaning of each option.

The pages that say 'Option -foo sets foo to true' are still there, but you have to work pretty hard to end up on one of them.

**Comment by swhobbit** [comment]
> The command-line options pages for each emulator now consist of a summary table giving the basic syntax and meaning of each option.

*Much* improved.

> The pages that say 'Option -foo sets foo to true' are still there, but you have to work pretty hard to end up on one of them.

Those and (especially) category pages, can be frustrating, but you may close this.  If I find a problematic page, I'll reopen this with a specific pointer to the offending page.

**Comment by pmattes** [comment]
The 'Option -foo sets foo to true' pages are now effectively gone. They are now redirects to the related resource pages, but still listing categories, so they are shown on the category pages.
