### ISSUE TITLE
wc3270 unable to log in to mainframe appliacation

### ISSUE THREAD

**Issue by mmamrot** [pmattes/x3270#45]
Mainframe application works. I am not able to log in to the application. When I write in a console wc3270.exe (address:4992)
then wc3270 window appears but after several seconds I got an informatio that Connection failed :
TLS: InitializeSecurityContext: error 0x80090325 (the certificte chain was issueed by an authority that is not trusted.)

I can log in to the mainframe using Jagacy library without any problem.
Does anyone know what could be a root cause of that?

**Comment by pmattes** [comment]
wc3270 uses the Windows sChannel APIs to implement TLS. I don't know what Jacagy might be using.

You can fix this in two ways. As a workaround, you can turn off host certificate checking. Add 'L:Y:' to your host, e.g., L:Y:address:4992. You can also get a copy of the CA root certificate from whoever signed your host's certificate, and install that in the Windows trusted certificate store.

**Comment by mmamrot** [comment]
Thank you a lot. It helps

**Comment by mmamrot** [comment]
Issue can be closed
