### ISSUE TITLE
[Not an issue] TN3270 protocol specification

### ISSUE THREAD

**Issue by lppedd** [pmattes/x3270#46]
Sorry to bother for such (maybe) simple questions.
I was wondering where to find the full TN3270 protocol specification. If I understood correctly multiple versions of that exist.
I'd like to have a read as I want to automate some tasks.

**Comment by pmattes** [comment]
The TN3270 protocol is covered here (with references to the RFCs):
https://x3270.miraheze.org/wiki/TELNET

The 3270 data stream protocol is covered here (with a reference to an original IBM document):
https://x3270.miraheze.org/wiki/3270_data_stream_protocol
