### ISSUE TITLE
ftRemap wiki description is wrong

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#55]
the [File Transfer Resources](https://x3270.miraheze.org/wiki/File_transfer_resources) wiki page looks wrong.  It is says:

> Mapping behavior for text files:
  yes: map between the workstation's locale and the host's [EBCDIC](https://x3270.miraheze.org/wiki/EBCDIC) [code page](https://x3270.miraheze.org/wiki/Host_code_page)
  no: use fixed [ISO 8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) <-> [EBCDIC](https://x3270.miraheze.org/wiki/EBCDIC) [code page 037](http://dictionary.sensagent.com/EBCDIC%20037/en-en/) translation

The `yes` option should point out the second-guessing of the host translation to `ASCII`.
The `no` option should say something like _translation between `EBCDIC` & `ASCII` is left up to the host `IND$FILE` program._

**Comment by pmattes** [comment]
Corrected.
