### ISSUE TITLE
x3270 S-t-r-e-t-c-h

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#56]
Since x3270 can't grow the number of rows or columns if user adjusts adjust the window size (*curse you TN3270E protocol!*), it should go the other way — iterate through its defined fonts to make window smaller/bigger to make maximum use of the new Window sizer.

**Comment by pmattes** [comment]
That's precisely what it does, as long as the 3270 fonts are installed and in the X11 font search path.

Is there some situation where this is not working?

**Comment by swhobbit** [comment]
Oops.

I **would** prefer the resized window snapped to the size of window it would used had the font menu instead been used instead.  Doing so by hand can make the font fallback to a smaller size.  (The excess size helps to hide large font.)

You can tweak **that** or close as is.

**Comment by pmattes** [comment]
There is menu action, Options -> Snap Window Size, which performs the snap operation explicitly.

The is no option to make the snap operation automatic. I tried a couple of different variations on that a few years ago, and none of them seemed to work intuitively. Approach 1: If you make the window bigger, use a bigger font (which might make the window bigger still than you asked for). Approach 2: If you make the window bigger but not big enough for the next font size, snap it back to the original size. Both of these got weird when you adjusted the window size asymmetrically (wider but shorter, for example). It feels like less of a surprise if the window stays at exactly the dimensions you choose, and x3270 finds the best font that fits those dimensions.

**Comment by swhobbit** [comment]
I'm aware of the Snap Window Size action.

So only snap after a font change resize it, and/or make it a boolean to do so.  Don't let perfect be the enemy of better.

**Comment by swhobbit** [comment]
> If you make the window bigger but not big enough for the next font size, snap it back to the original size. Both of these got weird when you adjusted the window size asymmetrically (wider but shorter, for example). It feels like less of a surprise if the window stays at exactly the dimensions you choose, and x3270 finds the best font that fits those dimensions.

It's waste of real estate to leave the window oversized for the font.  This is in fact I misdemeanor in 17 states and 2 territories.

**Comment by swhobbit** [comment]
> [pmattes](https://github.com/pmattes) closed this as `completed`

Minor point.  Thus should not been fixed as completed. The close button allows other reasons than for`completed`, and this was one of those other reasons.

**Comment by pmattes** [comment]
Okay, it is not planned rather than completed. The enhancement request for Ctrl-+/Ctrl-- is complete. I am taking the other size-related one under advisement.
