### ISSUE TITLE
pr3287 doesn't issue a good error for bad command line.

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#6]
### Overview:

I'd rather have a simple error message and a line suggesting how to display the full help than NO error message and a flood of options which cause the command I typed in to scroll of the screen (the terminal I was in didn't even scrollback!)

### Version:

pr3287 v4.0ga9 Wed May 27 17:32:08 UTC 2020 ahd
Build options: via gcc 8.3.0 32-bit

### Problem: 

`pr3287` doesn't issue an error message if command line has errors; it dumps a spew of **all** possible options

### How to reproduce:

 pr3287 -command spool.py -V PRT  @hercules:${HERCULES_PORT} 

### Expected behavior:

Precise error reporting bad or missing parameter 

### Current result:

<pre>
[wile:14,~/hercules/kew3,89] `pr3287 -command spool.py -V PRT  @hercules:3278`
usage: pr3287 [options] [lu[,lu...]@]host[:port]
Options:
  -accepthostname <name>
                   accept a specific name in host cert
  -assoc <session> associate with a session (TN3270E only)
  -cadir <dir>     find CA certificate database in <dir>
  -cafile <file>   find CA certificates in <file>
  -certfile <file> find client certificate in <file>
  -certfiletype pem|asn1
                   specify client certificate file type
  -chainfile <file>
                   specify client certificate chain file
  -codepage <name> specify host code page
  -command "<cmd>" use <cmd> for printing (default "lpr")
  -blanklines      display blank lines even if empty (formatted LU3)
  -daemon          become a daemon after connecting
  -emflush         flush printer output when an unformatted EM order arrives
                   (historical option; this is now the default)
  -noemflush       do not flush printer output when an unformatted EM order
                   arrives
  -crlf            expand newlines to CR/LF
  -crthru          pass through CRs in unformatted 3270 mode
  -eojtimeout <seconds>
                   time out end of print job
  -ffeoj           assume FF at the end of each print job
  -ffthru          pass through SCS FF orders
  -ffskip          skip FF orders at top of page
  -keyfile <file>  find certificate private key in <file>
  -keyfiletype pem|asn1
                   specify private key file type
  -keypasswd file:<file>|string:<string>
                   specify private key password
  -ignoreeoj       ignore PRINT-EOJ commands
  -mpp <n>         define the Maximum Presentation Position (unformatted
                   line length)
  -noverifycert    do not verify host certificate for TLS connections
  -proxy "<spec>" 
                   connect to host via specified proxy
  -reconnect       keep trying to reconnect
  -skipcc          skip ASA carriage control characters in unformatted host
                   output
  -syncport port   TCP port for login session synchronization
  -trace           trace data stream to /tmp/x3trc.<pid>
  -tracedir <dir>  directory to keep trace information in
  -trnpre <file>   file of transparent data to send before each job
  -trnpost <file>  file of transparent data to send after each job
  -v               display version information and exit
  -verifycert      verify host certificate for TLS connections (enabled by default)
  -V               log verbose information about connection negotiation
  -xtable <file>   specify a custom EBCDIC-to-ASCII translation table
</pre>

**Comment by pmattes** [comment]
You're right, I should do the option dump only on request, with --help or -?. This is true for all of the emulators, not just pr3287.

I will put this on the 4.0 to-do list.

**Comment by pmattes** [comment]
Fix is committed.
