### ISSUE TITLE
enhancement: Support font resize via keyboard using Ctrl- and Cntrl+

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#60]
The `x3270` emulator supports dragging the window border to resize the terminal font.  

Font resize should also be supported from the keyboard, in manner of Web Browsers. That is, resizing the font to the next step up or down should be supported is via `Ctrl-` (shrink) and `Ctrl+` (grow).

**Comment by pmattes** [comment]
Implemented in x3270 4.3.

**Comment by swhobbit** [comment]
On MacOS, the following default binding would match other applications:

        Meta<Key>plus:  StepEfont("Bigger")\n\
        Meta<Key>minus: StepEfont("Smaller")

**Comment by pmattes** [comment]
Done.

**Comment by swhobbit** [comment]
> Done.

Thanks!
