### ISSUE TITLE
c3270 in Window 11's CMD Terminal: mouse does not work :(

### ISSUE THREAD

**Issue by ssamayoa** [pmattes/x3270#61]
Window 11 removed old CMD and now opens "terminal" in which c3270's mouse does not work.

I know that I could use wx3270 but IMHO c3270 is more comfortable.

Any hint on how to restore mouse?

**Comment by pmattes** [comment]
Quick workaround:
- Right-click on the desktop shortcut for wc3270, or any of the desktop shortcuts created by the wc3270 Session Wizard, and select Properties. (On Win11, you might need to select 'Show more options' first.)
- Select the Shortcut tab and go to the Target: field.
- At the beginning of the Target; field, add the text 'conhost' (no quotes) and a space.

I will get out a fix with this change shortly.

**Comment by ssamayoa** [comment]
WOW!
That was quick!
**Thankyou sir!**

**Comment by pmattes** [comment]
It’s been a ticking time bomb since Windows 11 was changed to make Windows Terminal the default.I still need to make the code change to make this automatic.        pdmOn Jan 24, 2023, at 9:17 PM, Sergio Samayoa ***@***.***> wrote:﻿
Closed #61 as completed.
