### ISSUE TITLE
Help: Receiving "Host disconned" when running jobs from GitHub ubuntu-latest runners

### ISSUE THREAD

**Issue by robinmatz** [pmattes/x3270#63]
Hi Paul,

we host a project on GitHub where we run a pipeline against the pub400.com host. The jobs in the pipeline sometimes fail with the message Host disconnected. This error seems to occur randomly.

I will attach the trace of a failing job. Could you help me get some clues as to why this error occurs? I am suspecting some type of network issues...
[Atest.Mainframe-x3270-trace.txt](https://github.com/pmattes/x3270/files/10834521/Atest.Mainframe-x3270-trace.txt)

**Comment by Harm10** [comment]
Just my 2 cents: couldn't this be a defense from pub400 itself? It gets all kind of weird calls from utest and/or atest from the same IP address. I experienced this too and after a while the tests run fine again.

**Comment by pmattes** [comment]
There isn't much to go on in the trace. x3270 answers the host's Query Reply at 182519.809, and at 182519.986 (177 ms later) the host disconnects without having sent anything else.

From what you said, the exact same script succeeds most of the time? Perhaps pub400 is getting overloaded and this how it sheds work it can't do.

**Comment by robinmatz** [comment]
Thank you for the answers. I read on the pub400.com website that there is a restriction on how many connections can be made from a single IP address. 

I am suspecting that even though there is an IP range for the GitHub runners, there is a chance that some VMs can have the same IP address.

I am closing this issue now.
