### ISSUE TITLE
Prefer: you keep using that word

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#75]
The https://x3270.miraheze.org/wiki/PreferIpv4_resource states:

 `If this resource is set to true, only IPv4 addresses will be selected.`
 
_Prefer_ means _favorite_, not _only_. Please is either change the keyword or change the behavior.

**Comment by pmattes** [comment]
It really does mean 'prefer'. I will correct the Wiki as soon as I get write access to it again. :-(

**Comment by pmattes** [comment]
The Wiki has been corrected.
