### ISSUE TITLE
stepping up to too large a font error handling is incomplete

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#76]
On MacOS using `x3270` version 4.4pre1, I normally run font 3270gt24 in a 43 line screen. It almost fill the screen vertically and can be smaller with `CMD -`.  (Yea!)

**problem desc**: If I accidentally attempt to step the font up even further with `CMD +`, it tries to expand the windows, so it can set the font up.  However, it determines it can't _quite_ do it, and then gives up without restoring  the window.  Thus the font for the window now has a relatively undersized under sized font in it.  (See attached)

**expected behavior**: If stepping up the window doesn't work (it doesn't fit), the window size **and** font are restored so the font fills stills a `x3270` window which completely fits on the window. 

I thought when the step up command was first added, oversizing screen did recover completely. (_I'm not sure_.)

![Normal screen & failed oversized screen](https://github.com/pmattes/x3270/assets/16212073/22586c27-fd3a-400f-b499-c6d1b5c3e48a)
![Screen shot with configuration](https://github.com/pmattes/x3270/assets/16212073/5567a675-3a0c-40bb-a08a-b0d078a8890d)

**Comment by pmattes** [comment]
Earlier versions of x3270 attempted to recover from failed attempts to implicitly resize the screen (changing the font or model, turning on the integrated keypad, etc.) when the window ended up too big to fit. That logic was brittle and unreliable, and has been removed.

Now x3270 uses simpler, more deterministic logic. It accepts any request to resize the screen externally, whether that comes from the user grabbing a resize handle, or the window manager telling it that its attempt to grow the window to accommodate a larger font is invalid. (These two events are indistinguishable in the X11 protocol.) x3270 responds by adjusting the font to the largest size that fits in the requested rectangle, floating the 3270 display in the middle of that area.

The 'snap' menu option is available if you want the window size to be shrunk to the minimum necessary to accommodate the current configuration.
