### ISSUE TITLE
Feature request: Set _NET_WM_NAME to the window title

### ISSUE THREAD

**Issue by CheyenneWills** [pmattes/x3270#77]
Currently it is not possible to share a x3270 window via Zoom. It appears that Zoom will only share a window that has the X11 property _NET_WM_NAME set. 

If I manually set the _NET_WM_NAME via xprop, then the window can be shared on Zoom.

**Comment by pmattes** [comment]
It was a bit harder than I thought it was, but the code is complete and committed to 4.3 and master. I will be including it in a release shortly.

**Comment by CheyenneWills** [comment]
Works -- thanks

**Comment by pmattes** [comment]
Excellent!
