### ISSUE TITLE
ws3270 keyboard wrongly reported as unlocked in prompt-line

### ISSUE THREAD

**Issue by feujun** [pmattes/x3270#78]
Hi,
this behaviour is present in s3270 4.3.6 (on Windows) onwards.

### Describe the problem
When entering text into a protected field or a SF-field the keyboard is locked but the s3270-protocol prompt-line reports an unlocked keyboard like this:

`U F U C(<HOST>) I 4 24 80 6 26 0x0 0.007`

### To Reproduce
Position the cursor on a protected / SF-field and enter any character. My setup to reproduce includes the commands:

1. `movecursor1(7,27)`
2. `readbuffer(field)` (to verify I am on the right cursor-position, a SF)
3. `string("x")`

after execution of string("x") the emulator-output states:

> `data: Keyboard locked`
> `data: Operator error`
> `U F U C(<HOST>) I 4 24 80 6 26 0x0 0.007`

### Expected Behaviour
The keyboard is locked. The prompt-line should read `L F U ...` (like it did in 4.3.5 and before)

### TRACE
Here is the trace-file for the 3 steps above if that helps:

[x3trc.10232.txt](https://github.com/pmattes/x3270/files/14771563/x3trc.10232.txt)

If I can clarify anything else I will gladly do so :)

**Comment by pmattes** [comment]
Thank you for the perfect bug report! This will be fixed in 4.3.8.

**Comment by feujun** [comment]
Wow that was quick. Thanks you very much!
