### ISSUE TITLE
Function keys from F1-F23 works in Nvt mode but in 3270 mode i get error from terminal (Function key not allowed)

### ISSUE THREAD

**Issue by jhachandan1994** [pmattes/x3270#80]
Hi,
I am trying to pass function keys Pf-pf24 which works perfectly in nvt mode but in 3270 mode i am getting error in terminal as function keys not allowed. i want to emulate pressing f1-f24 keys.including tracefile for 3270 mode.

[tracefile.txt](https://github.com/pmattes/x3270/files/15180305/tracefile.txt)

**Comment by pmattes** [comment]
Let me guess that you are talking to an i Series (AS/400) host.

Check out this page: https://www.ibm.com/docs/en/i/7.2?topic=sessions-3270-keyboard-mapping-telnet-servers

When using a 3270 to talk to an i Series host, the 3270 PF3 key is interpreted as the 5250 Clear key, and the 3270 PF12 key is interpreted as the 5250 Record Backspace key. I will guess that these keys are not valid on the screen you are on. If you want the 5250 F3 key, you need to press PA1, PF3 on the 3270. If you want the 5250 F12 key, you need to press PA1, PF12 on the 3270.

I don't know if or why these rules might not apply in NVT mode.

**Comment by jhachandan1994** [comment]
@pmattes Thanks this is working.
