### ISSUE TITLE
Unknown action: SelectDown

### ISSUE THREAD

**Issue by dkelosky** [pmattes/x3270#82]
Several actions which I've bound to keys via something like ` <Key>U+0066: SelectDown()\n\` yield an error when starting `c3270`:

```
Keymap mine, line 7: error:
Unknown action: SelectDown
```

From [here](https://x3270.miraheze.org/wiki/Category:X3270_keymap-only_actions), I get errors for:
- `SelectDown()`
- `SelectUp()`
- `SelectRight()`
- `SelectLeft()`
- `Select-extend()`
- `KybdSelect()`

Am I using these incorrectly?  Other bindings work great `EraseEOF()`, `Attn()`, etc...

**Comment by pmattes** [comment]
Those are wc3270 actions. They don't work on c3270.
