### ISSUE TITLE
options missing for c3270 on Apple M1 Pro notebook macos 14.1.2

### ISSUE THREAD

**Issue by lightning-pro** [pmattes/x3270#85]
when I installed the x3270 4.3ga9 with command 'brew install x3270' reference by https://formulae.brew.sh/formula/x3270

The c3270 will be installed without x3270 GUI .

c3270 can access to the ZOS ,but no options menus like keypad in the terminal. 

because of this, after L CICS, no clear button can be pressed to clear the message in screen

**Comment by pmattes** [comment]
The default c3270 key mapping for the 3270 is Ctrl-C.

Also, if you start c3270 in a terminal window that has at least 27 rows, you will get a menu bar at the top, which includes an option to pop up a keypad overlay on the screen, which includes the Clear key.
