### ISSUE TITLE
Error: Mailformed environment

### ISSUE THREAD

**Issue by LTepliakov** [pmattes/x3270#86]
When I exit from x3270> prompt by typing / and then try to enter it again with File -> x3270> prompt, I am getting below error:

![image](https://github.com/user-attachments/assets/2822ccbd-710b-4bd4-91b6-6abc4ddbc683)

I can get rid of it only when I exit x3270 and start it again.
I am connected to z/VSE and go File -> x3270> when I have CICS command mode on the screen. Exiting and entering CICS command mode does not help.
I am on Ubuntu Linux. Below is my x3270 configuration:
![image](https://github.com/user-attachments/assets/43fce5a0-0776-4758-b832-52b86413744a)

If it is not a bug, appreciate your advice on how to troubleshoot that.

**Comment by pmattes** [comment]
That is some fairly old x3270 code. I would first suggest trying with the latest stable code (4.3ga9). If the issue persists, then we can figure out how to debug it. The code that manipulates the environment is not complex at all.

**Comment by LTepliakov** [comment]
Installed 4.3ga9 from source and this problem disappeared.
Thank you Paul!

**Comment by pmattes** [comment]
Excellent!
