### ISSUE TITLE
Transfer() action. Looks to be a typo on the wiki page.

### ISSUE THREAD

**Issue by LTepliakov** [pmattes/x3270#87]
On the wiki page: https://x3270.miraheze.org/wiki/Transfer()_action
There are number of examples like:
Transfer(host=vm,**mode=send**,localfile=file1,hostfile=file1)
Wait(CursorAt,-2,1)
Transfer(host=vm,**mode=send**,localfile=file2,hostfile=file2)
Wait(CursorAt,-2,1)
Transfer(host=vm,**mode=send**,localfile=file3,hostfile=file3)

x3270> Transfer(host=cics, mode=send, localfile=offer.dat, hostfile=MANAGED.SAM.FILE2)
Transfer(): Invalid option value: 'send'

It looks like a typo. mode parameter does not have send option.

Looks like should be 
direction=send instead of mode=send.

**Comment by pmattes** [comment]
Fixed.
