### ISSUE TITLE
Question: Full screen possible?

### ISSUE THREAD

**Issue by ILoveHubGit** [pmattes/x3270#9]
Is it possible to enlarge the terminal window or run it in full screen mode?

**Comment by pmattes** [comment]
If you are asking about x3270, screen resizing and full-screen mode works in 4.0, as long as you are using the 3270 fonts.

If you are asking about wc3270, this will never work; I suggest trying wx3270 instead.

**Comment by ILoveHubGit** [comment]
Thanks a lot. This is workable for us as well.
