### ISSUE TITLE
Create a License

### ISSUE THREAD

**Issue by Linesmerrill** [pmattes/x3270#93]
Hi, I am familiar with your project and I noticed that it does not have a license. I would like to suggest that you add a license to your project so it can be freely used, modified, repurposed, or shared by the open source community. You can find information on various licenses [here](https://opensource.org/licenses). To choose the right license for your project, check out [choosealicense.com](https://choosealicense.com/).

**Comment by pmattes** [comment]
What gave you the impression that x3270 does not have a license? Is there some convention on GitHub to indicate what your license is that I have somehow missed?

**Comment by Linesmerrill** [comment]
1. If you already have a license, I did not see it listed in the root files or linked inside the readme, my mistake. 

2. If this is not something that you would like the open source community to contribute to, totally fine you can close this issue.

3. If you do want others in the open source community to contribute, for legal reasons I would suggest you pick out a license. More details here [Adding a license to your repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by pmattes** [comment]
I did have a license file, and have had one from the outset, though it was buried a bit in the source tree. I appreciate your pointing this out. I have copied it to where GitHub will find it now.

I welcome contributions from the community. I'm not sure what would have given you the impression that I do not.
